# Problem Set IV - Data Preprocessing

In [48]:
import numpy as np
import pandas as pd
import re
from sklearn import preprocessing as pre
from sklearn.impute import SimpleImputer 

In [4]:
# Load data into pandas.DataFrame from Avocado Dataset.csv
avdata = pd.read_csv("./Avocado.csv")
avdata

Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0               0  27-12-2015          1.33      64236.62  1036.74   54454.85   
1               1  20-12-2015          1.35      54876.98   674.28   44638.81   
2               2  13-12-2015          0.93     118220.22   794.70  109149.67   
3               3  06-12-2015          1.08      78992.15  1132.00   71976.41   
4               4  29-11-2015          1.29      51039.60   941.48   43838.39   
...           ...         ...           ...           ...      ...        ...   
18245       18245  28-01-2018          1.71      13888.04  1191.70    3431.50   
18246       18246  21-01-2018          1.87      13766.76  1191.92    2452.79   
18247       18247  14-01-2018          1.93      16205.22  1527.63    2981.04   
18248       18248  07-01-2018          1.62      17489.58  2894.77    2356.13   
18249       18249  18-03-2018          1.56      15896.38  2055.35    1499.55   

         4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0       48.16     8696.87     8603.62       93.25          0.0  conventional   
1       58.33     9505.56     9408.07       97.49          0.0  conventional   
2      130.50     8145.35     8042.21      103.14          0.0  conventional   
3       72.58     5811.16     5677.40      133.76          0.0  conventional   
4       75.78     6183.95     5986.26      197.69          0.0  conventional   
...       ...         ...         ...         ...          ...           ...   
18245    0.00     9264.84     8940.04      324.80          0.0       organic   
18246  727.94     9394.11     9351.80       42.31          0.0       organic   
18247  727.01    10969.54    10919.54       50.00          0.0       organic   
18248  224.53    12014.15    11988.14       26.01          0.0       organic   
18249    0.00    12341.48    12114.81      226.67          0.0       organic   

       year            region Hierarchy  
0      2015            Albany       Old  
1      2015            Albany       Old  
2      2015            Albany       Old  
3      2015            Albany       Old  
4      2015            Albany       Old  
...     ...               ...       ...  
18245  2018  WestTexNewMexico    Recent  
18246  2018  WestTexNewMexico    Recent  
18247  2018  WestTexNewMexico    Recent  
18248  2018  WestTexNewMexico    Recent  
18249  2018  WestTexNewMexico    Recent  

[18250 rows x 15 columns]

In [5]:
# Load data into pandas.DataFrame from Avocado Dataset.csv
trdata = pd.read_csv("./Trail.csv")
trdata

Date AveragePrice  Total Volume     4046       4225    4770  \
0    20-12-2015         1.35      54876.98   674.28   44638.81   58.33   
1    13-12-2015         0.93     118220.22   794.70  109149.67  130.50   
2    06-12-2015         1.08      78992.15  1132.00   71976.41   72.58   
3    22-11-2015          NaN      55979.78  1184.27   48067.99   43.61   
4    20-12-2015         1.35      54876.98   674.28   44638.81   58.33   
..          ...          ...           ...      ...        ...     ...   
197  20-09-2015          NaN     498640.23  4376.74  398673.48  418.46   
198  13-09-2015          NaN     655682.95  5422.29  560792.23  353.77   
199  06-09-2015          NaN     577774.74  4237.44  477867.83  496.62   
200  30-08-2015          NaN     526664.87  4177.03  438502.90  554.04   
201  23-08-2015          NaN     589471.32  4744.11  488292.10  608.61   

     Total Bags  Small Bags  Large Bags  XLarge Bags          type  year  \
0       9505.56     9408.07       97.49          0.0  conventional  2015   
1       8145.35     8042.21      103.14          0.0  conventional  2015   
2       5811.16     5677.40      133.76          0.0  conventional  2015   
3       6683.91     6556.47      127.44          0.0  conventional  2015   
4       9505.56     9408.07       97.49          0.0  conventional  2015   
..          ...         ...         ...          ...           ...   ...   
197    95171.55    91612.66     3558.89          0.0  conventional  2015   
198    89114.66    84843.55     4271.11          0.0  conventional  2015   
199    95172.85    94558.41      614.44          0.0  conventional  2015   
200    83430.90    83242.01      188.89          0.0  conventional  2015   
201    95826.50    95585.38      241.12          0.0  conventional  2015   

     region  
0    Albany  
1    Albany  
2    Albany  
3    Albany  
4    Albany  
..      ...  
197  Boston  
198  Boston  
199  Boston  
200  Boston  
201  Boston  

[202 rows x 13 columns]

In [6]:
avdata.dtypes

Unnamed: 0        int64
Date             object
AveragePrice    float64
Total Volume    float64
4046            float64
4225            float64
4770            float64
Total Bags      float64
Small Bags      float64
Large Bags      float64
XLarge Bags     float64
type             object
year              int64
region           object
Hierarchy        object
dtype: object

1. Select a subset of relevant attributes from the given dataset that are necessary to know about thetotal volume of avocados with product lookup codes (PLU) 4046, 4225, 4770) which are of organic type. (Use AVOCADO dataset)


In [7]:
avdata['type'] = [x.strip() for x in avdata['type'].astype(str)]

In [8]:
orgData = pd.DataFrame([avdata.iloc[i] for i in avdata.index if avdata['type'].iloc[i] == 'organic'])

In [9]:
orgData[['Total Volume', "4046", "4225", "4770"]]

Total Volume     4046     4225    4770
9126         989.55     8.16    88.59    0.00
9127        1163.03    30.24   172.14    0.00
9128         995.96    10.44   178.70    0.00
9129        1158.42    90.29   104.18    0.00
9130         831.69     0.00    94.73    0.00
...             ...      ...      ...     ...
18245      13888.04  1191.70  3431.50    0.00
18246      13766.76  1191.92  2452.79  727.94
18247      16205.22  1527.63  2981.04  727.01
18248      17489.58  2894.77  2356.13  224.53
18249      15896.38  2055.35  1499.55    0.00

[9124 rows x 4 columns]

2. Discard all duplicate entries in the given dataset and fill all the missing values in the attribute “AveragePrice” as 1.25. Also print the size of the dataset before and after removing duplicates. (Use Trail dataset)


In [10]:
trdata.shape

(202, 13)

In [11]:
trdata = trdata.drop_duplicates()

In [12]:
trdata.shape

(195, 13)

In [13]:
is_number = lambda x: re.match(r'[+-]?[0-9]+\.?[0-9]*', str(x)) is not None

In [14]:
defaultAvgPrice = 1.25
for i in range(len(trdata)):
    print(i, trdata.iloc[i])
    if is_number(trdata.iloc[i]['AveragePrice']) == False:
        trdata.loc[i, 'AveragePrice'] = defaultAvgPrice
trdata

0 Date              20-12-2015
AveragePrice            1.35
Total Volume           54877
4046                  674.28
4225                 44638.8
4770                   58.33
Total Bags           9505.56
Small Bags           9408.07
Large Bags             97.49
XLarge Bags                0
type            conventional
year                    2015
region                Albany
Name: 0, dtype: object
1 Date              13-12-2015
AveragePrice            0.93
Total Volume          118220
4046                   794.7
4225                  109150
4770                   130.5
Total Bags           8145.35
Small Bags           8042.21
Large Bags            103.14
XLarge Bags                0
type            conventional
year                    2015
region                Albany
Name: 1, dtype: object
2 Date              06-12-2015
AveragePrice            1.08
Total Volume         78992.1
4046                    1132
4225                 71976.4
4770                   72.58
Total Bags          

/home/anant/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


Date AveragePrice  Total Volume     4046       4225    4770  \
0    20-12-2015         1.35      54876.98   674.28   44638.81   58.33   
1    13-12-2015         0.93     118220.22   794.70  109149.67  130.50   
2    06-12-2015         1.08      78992.15  1132.00   71976.41   72.58   
3    22-11-2015         1.25      55979.78  1184.27   48067.99   43.61   
5    13-12-2015         1.21     118220.22   794.70  109149.67  130.50   
..          ...          ...           ...      ...        ...     ...   
197  20-09-2015          NaN     498640.23  4376.74  398673.48  418.46   
198  13-09-2015          NaN     655682.95  5422.29  560792.23  353.77   
199  06-09-2015          NaN     577774.74  4237.44  477867.83  496.62   
200  30-08-2015          NaN     526664.87  4177.03  438502.90  554.04   
201  23-08-2015          NaN     589471.32  4744.11  488292.10  608.61   

     Total Bags  Small Bags  Large Bags  XLarge Bags          type  year  \
0       9505.56     9408.07       97.49          0.0  conventional  2015   
1       8145.35     8042.21      103.14          0.0  conventional  2015   
2       5811.16     5677.40      133.76          0.0  conventional  2015   
3       6683.91     6556.47      127.44          0.0  conventional  2015   
5       8145.35     8042.21      103.14          0.0      organic   2015   
..          ...         ...         ...          ...           ...   ...   
197    95171.55    91612.66     3558.89          0.0  conventional  2015   
198    89114.66    84843.55     4271.11          0.0  conventional  2015   
199    95172.85    94558.41      614.44          0.0  conventional  2015   
200    83430.90    83242.01      188.89          0.0  conventional  2015   
201    95826.50    95585.38      241.12          0.0  conventional  2015   

     region  
0    Albany  
1    Albany  
2    Albany  
3    Albany  
5      xxxx  
..      ...  
197  Boston  
198  Boston  
199  Boston  
200  Boston  
201  Boston  

[195 rows x 13 columns]

3. Binarize the attribute “Year”. Set the threshold above 2016 and print it without truncation. (Use AVOCADO dataset)

In [15]:
pre.binarize(avdata['year'].values.reshape(-1, 1), 2016)

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

4. Transform all categorical attributes in the dataset AVOCADO using Integer Encoding.

In [16]:
pre.OrdinalEncoder(avdata)

OrdinalEncoder(categories=       Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0               0  27-12-2015          1.33      64236.62  1036.74   54454.85   
1               1  20-12-2015          1.35      54876.98   674.28   44638.81   
2               2  13-12-2015          0.93     118220.22   794.70  109149.67   
3               3  06-12-2015          1.08      78992.15  1132.00   71976.41   
4               4  29-11-2015          1.29      51039.60   941.48   43838.39   
...           ...         ...           ...           ...      ...        ...   
18245       18245  28-01-2018          1.71      13888.04  1191.70    3431.50   
18246       18246  21-01-20...
18248  224.53    12014.15    11988.14       26.01          0.0       organic   
18249    0.00    12341.48    12114.81      226.67          0.0       organic   

       year            region Hierarchy  
0      2015            Albany       Old  
1      2015            Albany       Old  
2      2

5. Transform the attribute = “Region” in the given dataset AVOCADO using One-Hot Encoding.

In [17]:
pre.OneHotEncoder(avdata['region'])

OneHotEncoder(categories=0                  Albany
1                  Albany
2                  Albany
3                  Albany
4                  Albany
               ...       
18245    WestTexNewMexico
18246    WestTexNewMexico
18247    WestTexNewMexico
18248    WestTexNewMexico
18249    WestTexNewMexico
Name: region, Length: 18250, dtype: object,
              drop=None, dtype=<class 'numpy.float64'>, handle_unknown='error',
              sparse=True)

6. Ignore the tuples that hold missing values and print the subset of data from AVOCADO dataset.

In [18]:
avdata.dropna()

Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0               0  27-12-2015          1.33      64236.62  1036.74   54454.85   
1               1  20-12-2015          1.35      54876.98   674.28   44638.81   
2               2  13-12-2015          0.93     118220.22   794.70  109149.67   
3               3  06-12-2015          1.08      78992.15  1132.00   71976.41   
4               4  29-11-2015          1.29      51039.60   941.48   43838.39   
...           ...         ...           ...           ...      ...        ...   
18245       18245  28-01-2018          1.71      13888.04  1191.70    3431.50   
18246       18246  21-01-2018          1.87      13766.76  1191.92    2452.79   
18247       18247  14-01-2018          1.93      16205.22  1527.63    2981.04   
18248       18248  07-01-2018          1.62      17489.58  2894.77    2356.13   
18249       18249  18-03-2018          1.56      15896.38  2055.35    1499.55   

         4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0       48.16     8696.87     8603.62       93.25          0.0  conventional   
1       58.33     9505.56     9408.07       97.49          0.0  conventional   
2      130.50     8145.35     8042.21      103.14          0.0  conventional   
3       72.58     5811.16     5677.40      133.76          0.0  conventional   
4       75.78     6183.95     5986.26      197.69          0.0  conventional   
...       ...         ...         ...         ...          ...           ...   
18245    0.00     9264.84     8940.04      324.80          0.0       organic   
18246  727.94     9394.11     9351.80       42.31          0.0       organic   
18247  727.01    10969.54    10919.54       50.00          0.0       organic   
18248  224.53    12014.15    11988.14       26.01          0.0       organic   
18249    0.00    12341.48    12114.81      226.67          0.0       organic   

       year            region Hierarchy  
0      2015            Albany       Old  
1      2015            Albany       Old  
2      2015            Albany       Old  
3      2015            Albany       Old  
4      2015            Albany       Old  
...     ...               ...       ...  
18245  2018  WestTexNewMexico    Recent  
18246  2018  WestTexNewMexico    Recent  
18247  2018  WestTexNewMexico    Recent  
18248  2018  WestTexNewMexico    Recent  
18249  2018  WestTexNewMexico    Recent  

[18250 rows x 15 columns]

7. Drop the attribute that has high nullity as it facilitates efficient prediction. (Use AVOCADO dataset)

In [19]:
avdata.loc[:, avdata.isnull().mean() < .6]

Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0               0  27-12-2015          1.33      64236.62  1036.74   54454.85   
1               1  20-12-2015          1.35      54876.98   674.28   44638.81   
2               2  13-12-2015          0.93     118220.22   794.70  109149.67   
3               3  06-12-2015          1.08      78992.15  1132.00   71976.41   
4               4  29-11-2015          1.29      51039.60   941.48   43838.39   
...           ...         ...           ...           ...      ...        ...   
18245       18245  28-01-2018          1.71      13888.04  1191.70    3431.50   
18246       18246  21-01-2018          1.87      13766.76  1191.92    2452.79   
18247       18247  14-01-2018          1.93      16205.22  1527.63    2981.04   
18248       18248  07-01-2018          1.62      17489.58  2894.77    2356.13   
18249       18249  18-03-2018          1.56      15896.38  2055.35    1499.55   

         4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0       48.16     8696.87     8603.62       93.25          0.0  conventional   
1       58.33     9505.56     9408.07       97.49          0.0  conventional   
2      130.50     8145.35     8042.21      103.14          0.0  conventional   
3       72.58     5811.16     5677.40      133.76          0.0  conventional   
4       75.78     6183.95     5986.26      197.69          0.0  conventional   
...       ...         ...         ...         ...          ...           ...   
18245    0.00     9264.84     8940.04      324.80          0.0       organic   
18246  727.94     9394.11     9351.80       42.31          0.0       organic   
18247  727.01    10969.54    10919.54       50.00          0.0       organic   
18248  224.53    12014.15    11988.14       26.01          0.0       organic   
18249    0.00    12341.48    12114.81      226.67          0.0       organic   

       year            region Hierarchy  
0      2015            Albany       Old  
1      2015            Albany       Old  
2      2015            Albany       Old  
3      2015            Albany       Old  
4      2015            Albany       Old  
...     ...               ...       ...  
18245  2018  WestTexNewMexico    Recent  
18246  2018  WestTexNewMexico    Recent  
18247  2018  WestTexNewMexico    Recent  
18248  2018  WestTexNewMexico    Recent  
18249  2018  WestTexNewMexico    Recent  

[18250 rows x 15 columns]


8. Study the entire dataset and report the complete statistical summary about the data (Use AVOCADO
    dataset)
    (For the below exercises, you are free to choose an appropriate data set as merited by the problem statements)

- Dimension of the dataset


In [20]:
avdata.shape

(18250, 15)

- Most frequently occurring value under every attribute.


In [21]:
print(*[(x, avdata[x].value_counts().idxmax()) for x in avdata], sep= '\n')

('Unnamed: 0', 2047)
('Date', '18-03-2018')
('AveragePrice', 1.15)
('Total Volume', 19634.24)
('4046', 0.0)
('4225', 0.0)
('4770', 0.0)
('Total Bags', 0.0)
('Small Bags', 0.0)
('Large Bags', 0.0)
('XLarge Bags', 0.0)
('type', 'conventional')
('year', 2017)
('region', 'Albany')
('Hierarchy', 'Old')


- Datatype of every attribute


In [22]:
avdata.dtypes

Unnamed: 0        int64
Date             object
AveragePrice    float64
Total Volume    float64
4046            float64
4225            float64
4770            float64
Total Bags      float64
Small Bags      float64
Large Bags      float64
XLarge Bags     float64
type             object
year              int64
region           object
Hierarchy        object
dtype: object

- Count


In [23]:
avdata.count()

Unnamed: 0      18250
Date            18250
AveragePrice    18250
Total Volume    18250
4046            18250
4225            18250
4770            18250
Total Bags      18250
Small Bags      18250
Large Bags      18250
XLarge Bags     18250
type            18250
year            18250
region          18250
Hierarchy       18250
dtype: int64

- Mean


In [24]:
avdata.mean()

Unnamed: 0        9124.500000
AveragePrice         1.406852
Total Volume    850598.273413
4046            292992.481896
4225            295138.477670
4770             22838.484500
Total Bags      239626.747390
Small Bags      182185.367250
Large Bags       54335.123135
XLarge Bags       3106.256292
year              2016.148000
dtype: float64

- Standard Deviation


In [25]:
avdata.std()

Unnamed: 0      5.268466e+03
AveragePrice    4.024822e-01
Total Volume    3.453456e+06
4046            1.264956e+06
4225            1.204089e+06
4770            1.074613e+05
Total Bags      9.862168e+05
Small Bags      7.461591e+05
Large Bags      2.439596e+05
XLarge Bags     1.769242e+04
year            9.400127e-01
dtype: float64

- Minimum Value


In [26]:
avdata.min()

Unnamed: 0                 0
Date              01-01-2017
AveragePrice            0.44
Total Volume           84.56
4046                       0
4225                       0
4770                       0
Total Bags                 0
Small Bags                 0
Large Bags                 0
XLarge Bags                0
type            conventional
year                    2015
region                Albany
Hierarchy                New
dtype: object

- Maximum value

In [27]:
avdata.max()

Unnamed: 0                 18249
Date                  31-12-2017
AveragePrice                3.25
Total Volume         6.25056e+07
4046                 2.27436e+07
4225                 2.04706e+07
4770                 2.54644e+06
Total Bags           1.93731e+07
Small Bags           1.33846e+07
Large Bags            5.7191e+06
XLarge Bags               551694
type                     organic
year                        2018
region          WestTexNewMexico
Hierarchy                 Recent
dtype: object

- 25% (Lower Quartile)
- Median i.e. 50%
- 75% (Upper Quartile)


In [29]:
avdata.quantile([0.25,0.5,0.75])

Unnamed: 0  AveragePrice  Total Volume         4046         4225  \
0.25     4562.25          1.10    10839.6275     854.2100    3008.0975   
0.50     9124.50          1.37   107365.5050    8643.2000   29058.8750   
0.75    13686.75          1.66   432952.6650  111008.7125  150166.3350   

          4770   Total Bags  Small Bags  Large Bags  XLarge Bags    year  
0.25     0.000    5089.0825   2850.3225     127.580       0.0000  2015.0  
0.50   184.975   39741.1800  26351.6150    2647.270       0.0000  2016.0  
0.75  6242.055  110781.1150  83336.2100   22018.275     132.4325  2017.0

- Find whether the class distribution of dataset is imbalanced. (Note: Fix the class label as “Type” in the given dataset)



In [38]:
avdata.type.value_counts()
# count doesn't vary too much wrt type and hence the data is not imbalanced class distribution 

conventional    9126
organic         9124
Name: type, dtype: int64

- Correlation matrix


In [40]:
avdata.corr()

Unnamed: 0  AveragePrice  Total Volume      4046      4225  \
Unnamed: 0      1.000000      0.576975     -0.168408 -0.166762 -0.184927   
AveragePrice    0.576975      1.000000     -0.193116 -0.208891 -0.172971   
Total Volume   -0.168408     -0.193116      1.000000  0.977863  0.974181   
4046           -0.166762     -0.208891      0.977863  1.000000  0.926110   
4225           -0.184927     -0.172971      0.974181  0.926110  1.000000   
4770           -0.185298     -0.179811      0.872203  0.833390  0.887855   
Total Bags     -0.129854     -0.177532      0.963047  0.920057  0.905788   
Small Bags     -0.137209     -0.175129      0.967238  0.925280  0.916031   
Large Bags     -0.097911     -0.173481      0.880640  0.838645  0.810016   
XLarge Bags    -0.101632     -0.118026      0.747158  0.699378  0.688809   
year            0.475198      0.090644      0.017165  0.003328 -0.009584   

                  4770  Total Bags  Small Bags  Large Bags  XLarge Bags  \
Unnamed: 0   -0.185298   -0.129854   -0.137209   -0.097911    -0.101632   
AveragePrice -0.179811   -0.177532   -0.175129   -0.173481    -0.118026   
Total Volume  0.872203    0.963047    0.967238    0.880640     0.747158   
4046          0.833390    0.920057    0.925280    0.838645     0.699378   
4225          0.887855    0.905788    0.916031    0.810016     0.688809   
4770          1.000000    0.792315    0.802733    0.698472     0.679862   
Total Bags    0.792315    1.000000    0.994335    0.943009     0.804233   
Small Bags    0.802733    0.994335    1.000000    0.902589     0.806845   
Large Bags    0.698472    0.943009    0.902589    1.000000     0.710859   
XLarge Bags   0.679862    0.804233    0.806845    0.710859     1.000000   
year         -0.036550    0.071520    0.063883    0.087858     0.081005   

                  year  
Unnamed: 0    0.475198  
AveragePrice  0.090644  
Total Volume  0.017165  
4046          0.003328  
4225         -0.009584  
4770         -0.036550  
Total Bags    0.071520  
Small Bags    0.063883  
Large Bags    0.087858  
XLarge Bags   0.081005  
year          1.000000

- Skewness of every attribute.


In [41]:
avdata.skew()

Unnamed: 0       0.000000
AveragePrice     0.575674
Total Volume     9.007930
4046             8.648456
4225             8.942706
4770            10.159671
Total Bags       9.756334
Small Bags       9.540917
Large Bags       9.796719
XLarge Bags     13.140106
year             0.215371
dtype: float64

9. Test drive the use of Gini Index, Information Gain, Entropy and other measures that are supported in your platform, performing the role of data selection.


10. Test drive the implementation support in your platform of choice for data preprocessing phases such as cleaning, selection, transformation, integration in addition to the earlier exercises.

In [62]:
imputer = SimpleImputer(missing_values=np.nan,strategy = "mean") 
imputer.fit(avdata['Total Volume'].values.reshape(-1, 1))
imputer.fit(avdata['AveragePrice'].values.reshape(-1, 1))

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)